version: "3.5"
services:
  app:
    container_name: "${PROJECT_NAME}-app"
    image: trabalho
    build:
      context: .
      dockerfile: ./Dockerfile
      target: ${APP_ENV}
    volumes:
      - ./:/var/www/html
    environment:
      - XDEBUG_START_WITH_REQUEST=yes
      - XDEBUG_DISCOVER_CLIENT_HOST=false
    ports:
      - "${DOCKER_APP_PORT}:80"
    networks:
      - trabalho
  postgres:
    container_name: "${PROJECT_NAME}-db-postgres"
    image: postgres:14
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME_POSTGRES}
      POSTGRES_PASSWORD: ${DB_PASSWORD_POSTGRES}
      PGDATA: /data/postgres
    volumes:
      - ./.docker/data/postgres:/data/postgres
    ports:
      - "${DOCKER_POSTGRES_PORT}:5432"
    networks:
      - trabalho
    restart: unless-stopped

  pgadmin:
    container_name: "${PROJECT_NAME}-db-pgadmin"
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "${PGADMIN_DEFAULT_EMAIL}"
      PGADMIN_DEFAULT_PASSWORD: "${PGADMIN_DEFAULT_PASSWORD}"
    volumes:
       - ./.docker/data/pgadmin:/root/.pgadmin
       - ./pg_storage:/var/lib/pgadmin/storage
    ports:
      - "${DOCKER_PGADMIN_PORT}:80"
    networks:
      - trabalho
    restart: unless-stopped


networks:
  trabalho:
    name:   trabalho
    driver: bridge
